:toc: right
:backend: html5
:doctitle: Living Documentation
:doctype: book
:icons: font
:!numbered:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 2

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<An-example>>*
|1
|0
|1
|3
|0
|0
|0
|0
|0
|3
|001ms
|[green]#*passed*#

12+^|*<<Is-it-Friday?>>*
|3
|0
|3
|9
|0
|0
|0
|0
|0
|9
|004ms
|[green]#*passed*#
12+^|*Totals*
|4|0|4|12|0|0|0|0|0|12 2+|005ms
|===

== *Features*

[[An-example, An example]]
=== *An example*

ifndef::backend-pdf[]
minmax::An-example[]
endif::[]
==== Scenario: The example

==========
Given ::
an example scenario icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
When ::
all step definitions are implemented icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
the scenario passes icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
==========

[[Is-it-Friday?, Is it Friday?]]
=== *Is it Friday?*

ifndef::backend-pdf[]
minmax::Is-it-Friday?[]
endif::[]
==== Scenario Outline: Is it Friday?

==========
Given ::
today is "Friday" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
When ::
I ask whether it's Friday yet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
I should be told "TGIF" icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
==========

==== Scenario Outline: Is it Friday?

==========
Given ::
today is "Sunday" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
When ::
I ask whether it's Friday yet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
I should be told "No" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
==========

==== Scenario Outline: Is it Friday?

==========
Given ::
today is "anything else!" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
When ::
I ask whether it's Friday yet icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
I should be told "No" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
==========

